server:
  port: 8087

management:
  zipkin:
    tracing:
      endpoint:  http://127.0.0.1:9411/api/v2/spans # Эндпоинт Zipkin для приёма спанов
  tracing:
    sampling:
      probability: 1 # Сэмплируем все запросы
  endpoints:
    web:
      exposure:
        include: '*'


spring:
  application:
    name: blocker-api
#  config:
#    import: 'optional:consul:'
#  cloud:
#    consul:
#      host: localhost
#      port: 8500
#      discovery:
#        register-health-check: false
#      config:
#        enabled: true
#        format: yaml
#        prefix: config
#        defaultContext: application

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8089/realms/bank