apiVersion: v1
kind: Service
metadata:
  name: {{ include "kafka.fullname" . }}
  labels:
    {{- include "kafka.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: client
      port: 9092
      targetPort: 9092
      protocol: TCP
    - name: controller
      port: 29093
      targetPort: 29093
      protocol: TCP
  selector:
    {{- include "kafka.selectorLabels" . | nindent 4 }}
