services:
  postgresql:
    image: bitnami/postgresql:latest
    container_name: postgresql_one
    ports:
      - "5432:5432"
    environment:
      - POSTGRESQL_USERNAME=postgres
      - POSTGRESQL_PASSWORD=admin
      - POSTGRESQL_DATABASE=bank
