replicaCount: 1

image:
  repository: exchange-api
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 8084

ingress:
  enabled: false

autoscaling:
  enabled: false

resources: {}

initContainers:
  - name: wait-for-postgres
    image: busybox:1.36
    command: ['sh', '-c', 'until nc -z bank-app-postgresql 5432; do echo "Waiting for Postgres..."; sleep 3; done']
  - name: wait-for-keycloak
    image: busybox:1.36
    command: ['sh', '-c', 'until nc -z bank-app-keycloak 8080; do echo "Waiting for Keycloak..."; sleep 3; done']

readinessProbe:
  httpGet:
    path: /actuator/health
    port: 8084
  initialDelaySeconds: 30
  periodSeconds: 10

livenessProbe:
  httpGet:
    path: /actuator/health
    port: 8084
  initialDelaySeconds: 30
  periodSeconds: 20

serviceAccount:
  create: false
  name: default
  automount: false