replicaCount: 1

image:
  repository: transfer-api
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 8083

ingress:
  enabled: false

autoscaling:
  enabled: false

resources: {}

initContainers:
  - name: wait-for-accounts-api
    image: busybox:1.36
    command: ['sh', '-c', 'until nc -z bank-app-accounts-api 8081; do echo "Waiting for notifications-api..."; sleep 3; done']

readinessProbe:
  httpGet:
    path: /actuator/health
    port: 8083
  initialDelaySeconds: 30
  periodSeconds: 10

livenessProbe:
  httpGet:
    path: /actuator/health
    port: 8083
  initialDelaySeconds: 30
  periodSeconds: 20

serviceAccount:
  create: false
  name: default
  automount: false