server:
  port: 8082

spring:
  application:
    name: cash-api
  config:
    import: 'optional:consul:'
  cloud:
    consul:
      host: localhost
      port: 8500
      config:
        format: yaml
        data-key: data
        enabled: true
      discovery:
        register-health-check: false

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8089/realms/bank
      client:
        provider:
          keycloak:
            issuer-uri: http://localhost:8089/realms/bank
        registration:
          keycloak:
            provider: keycloak
            client-id: cash-api
            client-secret: y1rjV0oFXueYOf9f8LwqQYbtQTSgPFpK
            scope: profile
            authorizationGrantType: client_credentials
            clientAuthenticationMethod: client_secret_post