server:
  port: 8080

spring:
  application:
    name: front-ui
  config:
    import: 'optional:consul:'
  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        register-health-check: false
      config:
        enabled: true
        format: yaml
        prefix: config
        defaultContext: application
  security:
    oauth2:
      client:
        provider:
          keycloak:
            issuer-uri: http://localhost:8089/realms/bank
        registration:
          keycloak:
            provider: keycloak
            client-id: front-ui
            client-secret: wX41XDcC9N5FFvbvuGUpARTz7n6H5raF
            scope: profile
            authorizationGrantType: client_credentials
            clientAuthenticationMethod: client_secret_post
