server:
  port: 8080

spring:
  application:
    name: front-ui
  config:
    import: 'optional:consul:'
  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        register-health-check: false
  security:
    oauth2:
      client:
        provider:
          keycloak:
            issuer-uri: http://localhost:8089/realms/bank # Адрес сервера авторизации для получения токена
        registration:
          keycloak:
            provider: keycloak
            client-id: front-ui
            client-secret: wX41XDcC9N5FFvbvuGUpARTz7n6H5raF
            scope: profile
            authorizationGrantType: client_credentials
            clientAuthenticationMethod: client_secret_post # Способ передачи секрета
            #redirect-uri: '{baseUrl}/{action}/oauth2/code/{registrationId}'
            #issuer-uri=${ISSUER_URI:http://localhost:8089/realms/front-ui}: