server:
  port: 8080

spring:
  application:
    name: front-ui
  config:
    import: 'optional:consul:'
  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        register-health-check: false