pipeline {
    agent any

    stages {
        stage('Deploy Zipkin') {
            steps {
                script {
                    // Добавляем репозиторий zipkin (если еще не добавлен)
                    sh 'helm repo add zipkin https://zipkin.io/zipkin-helm || true'
                    sh 'helm repo update'

                    // Деплоим Zipkin
                    sh '''
                        helm upgrade --install bank-app-zipkin zipkin/zipkin \
                          --namespace default \
                          --version 0.4.0 \
                          --set zipkin.enabled=true \
                          --set zipkin.service.type=ClusterIP \
                          --set zipkin.service.port=9411 \
                          --set zipkin.persistence.enabled=false
                    '''
                }
            }
        }
    }
}
