pipeline {
    agent any

    environment {
        SHARED_REPO = '../shared/bankapp' // рабочая папка на jenkins
        IMAGE_NAME = "prometheus" // название образа
    }

    stages {
        stage('Get from github') {
            steps {
                dir("${SHARED_REPO}") {
                    echo 'get'
                    git branch: 'metrics', url: 'https://github.com/springRill/bankapp.git'
                }
            }
        }

        stage('Deploy Prometheus') {
            steps {
                dir("${SHARED_REPO}/bank-app/charts/${IMAGE_NAME}") {
                    sh """
                    helm upgrade --install bank-app-prometheus . \
                      --namespace default \
                      --create-namespace \
                      --set ingress.enabled=true \
                      --set ingress.className=nginx \
                      --set ingress.hosts[0].host=prometheus \
                      --set ingress.hosts[0].paths[0].path=/ \
                      --set ingress.hosts[0].paths[0].pathType=Prefix
                    """
                }
            }
        }
    }

}
