replicaCount: 1

image:
  repository: notifications-api
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 8086

ingress:
  enabled: false

autoscaling:
  enabled: false

resources: {}

initContainers:
  - name: wait-for-blocker-api
    image: busybox:1.36
    command: ['sh', '-c', 'until nc -z bank-app-blocker-api 8087; do echo "Waiting for blocker-api..."; sleep 3; done']

readinessProbe:
  httpGet:
    path: /actuator/health
    port: 8086
  initialDelaySeconds: 30
  periodSeconds: 10

livenessProbe:
  httpGet:
    path: /actuator/health
    port: 8086
  initialDelaySeconds: 30
  periodSeconds: 20

serviceAccount:
  create: false
  name: default
  automount: false