replicaCount: 1

image:
  repository: cash-api
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 8082

ingress:
  enabled: false

autoscaling:
  enabled: false

resources: {}

initContainers:
  - name: wait-for-transfer-api
    image: busybox:1.36
    command: ['sh', '-c', 'until nc -z bank-app-transfer-api 8083; do echo "Waiting for transfer-api..."; sleep 3; done']

readinessProbe:
  httpGet:
    path: /actuator/health
    port: 8082
  initialDelaySeconds: 30
  periodSeconds: 10

livenessProbe:
  httpGet:
    path: /actuator/health
    port: 8082
  initialDelaySeconds: 30
  periodSeconds: 20

serviceAccount:
  create: false
  name: default
  automount: false