apiVersion: v1
kind: Config
clusters:
  - cluster:
      server: https://192.168.49.2:8443
      #server: https://host.docker.internal:8443
      insecure-skip-tls-verify: true
    name: minikube
contexts:
  - context:
      cluster: minikube
      namespace: default
      user: minikube
    name: minikube
current-context: minikube
users:
  - name: minikube
    user:
      client-certificate: /root/.minikube/profiles/minikube/client.crt
      client-key: /root/.minikube/profiles/minikube/client.key
