server:
  port: 8085

spring:
  application:
    name: exchange-generator
  config:
    import: 'optional:consul:'
  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        register-health-check: false
      config:
        enabled: true
        format: yaml
        prefix: config
        defaultContext: application

  security:
    oauth2:
      client:
        provider:
          keycloak:
            issuer-uri: http://localhost:8089/realms/_bank
        registration:
          keycloak:
            provider: keycloak
            client-id: exchange-generator
            client-secret: KFkcoWi5ygHvZeudTTt06ShOtZ3BgMj8
            scope: profile
            authorizationGrantType: client_credentials
            clientAuthenticationMethod: client_secret_post

message:
  text: сообщение из yaml