server:
  port: 8085

spring:
  application:
    name: exchange-generator-api
  config:
    import: 'optional:consul:'
  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        register-health-check: false
