server:
  port: 8086

spring:
  application:
    name: notifications-api
  config:
    import: 'optional:consul:'
  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        register-health-check: false

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8089/realms/bank